# Generated by Django 3.1.4 on 2021-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_create_orchestra',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
