# Generated by Django 3.1.4 on 2021-06-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210217_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(editable=False, max_length=15, verbose_name='国'),
        ),
    ]
