# Generated by Django 3.1.4 on 2021-06-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210607_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='日本', editable=False, max_length=15, verbose_name='国'),
        ),
    ]
