# Generated by Django 3.1.4 on 2021-06-28 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orchestra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestra',
            name='admin_users',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orchestra',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
