# Generated by Django 3.1.4 on 2021-02-06 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orchestra', '0004_auto_20210110_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestra',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='orchestra',
            name='admin_users',
        ),
        migrations.AddField(
            model_name='orchestra',
            name='admin_users',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
