# Generated by Django 3.1.4 on 2021-02-16 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orchestra', '0005_auto_20210206_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchestra',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='orchestra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orchestra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
